export default [{ label: 'ALEPPO : ALEPPO' },
{ label: 'ALEPPO : Abi Fares al-Hamdani roundabout' },
{ label: 'ALEPPO : Akramiyah' },
{ label: 'ALEPPO : Ameriyah' },
{ label: 'ALEPPO : Ansari' },
{ label: 'ALEPPO : Aqabeh' },
{ label: 'ALEPPO : Aqioul' },
{ label: 'ALEPPO : Arqoub' },
{ label: 'ALEPPO : Ashrafiyeh' },
{ label: 'ALEPPO : Asilah' },
{ label: 'ALEPPO : Azamiyeh' },
{ label: 'ALEPPO : Bab al-Hadid' },
{ label: 'ALEPPO : Bab Jnein' },
{ label: 'ALEPPO : Bab al-Nasr' },
{ label: 'ALEPPO : Bab Nayrab' },
{ label: 'ALEPPO : Bab Road' },
{ label: 'ALEPPO : Ba\'idin' },
{ label: 'ALEPPO : Bani Zeid' },
{ label: 'ALEPPO : Banqusa' },
{ label: 'ALEPPO : Balleramoun' },
{ label: 'ALEPPO : Bayadah' },
{ label: 'ALEPPO : Bustan al-Basha' },
{ label: 'ALEPPO : Bustan al-Zahra' },
{ label: 'ALEPPO : Feid' },
{ label: 'ALEPPO : Hamidiyeh' },
{ label: 'ALEPPO : Thakanet Hananu' },
{ label: 'ALEPPO : Haydariyah' },
{ label: 'ALEPPO : Hazzazeh' },
{ label: 'ALEPPO : Helwaniyah' },
{ label: 'ALEPPO : Iza\'ah' },
{ label: 'ALEPPO : Jadet al-Khandaq' },
{ label: 'ALEPPO : Jalloum' },
{ label: 'ALEPPO : Jamiyat Mohandasin' },
{ label: 'ALEPPO : Jandoul' },
{ label: 'ALEPPO : Jazmati' },
{ label: 'ALEPPO : Karah Bridge' },
{ label: 'ALEPPO : Karam al-Beek' },
{ label: 'ALEPPO : Karam al-Jabal' },
{ label: 'ALEPPO : Karam al-Qaterji' },
{ label: 'ALEPPO : Kawakibi' },
{ label: 'ALEPPO : Kayyali St.' },
{ label: 'ALEPPO : Khan al-Harir' },
{ label: 'ALEPPO : Ma\'adi' },
{ label: 'ALEPPO : Maghayer' },
{ label: 'ALEPPO : Manshiyah al-Qadimeh' },
{ label: 'ALEPPO : Marjeh' },
{ label: 'ALEPPO : Martini' },
{ label: 'ALEPPO : Masaken Shebabi' },
{ label: 'ALEPPO : Mashhad' },
{ label: 'ALEPPO : Masharqah' },
{ label: 'ALEPPO : Maysser' },
{ label: 'ALEPPO : Maysaloun' },
{ label: 'ALEPPO : Meridian' },
{ label: 'ALEPPO : Midan' },
{ label: 'ALEPPO : Military Academy' },
{ label: 'ALEPPO : Mohafaza' },
{ label: 'ALEPPO : Mokambo' },
{ label: 'ALEPPO : Mushatiyeh' },
{ label: 'ALEPPO : Nile St.' },
{ label: 'ALEPPO : Qadi Asker' },
{ label: 'ALEPPO : Qarleq' },
{ label: 'ALEPPO : Qastal Mosht' },
{ label: 'ALEPPO : Rasafeh' },
{ label: 'ALEPPO : Rashiddin' },
{ label: 'ALEPPO : Sabaa Bahrat' },
{ label: 'ALEPPO : Sabil' },
{ label: 'ALEPPO : Salah al-Din' },
{ label: 'ALEPPO : Salaheen' },
{ label: 'ALEPPO : Sijan St.' },
{ label: 'ALEPPO : Sanam Bridge' },
{ label: 'ALEPPO : Sayed Ali' },
{ label: 'ALEPPO : Seif al-Dawleh' },
{ label: 'ALEPPO : Shahba' },
{ label: 'ALEPPO : Alshaar' },
{ label: 'ALEPPO : Sheikh Fares' },
{ label: 'ALEPPO : Sheikh Khader' },
{ label: 'ALEPPO : Sheirran' },
{ label: 'ALEPPO : Souq al-Hal' },
{ label: 'ALEPPO : Sukkari' },
{ label: 'ALEPPO : Suleiman al-Halabi' },
{ label: 'ALEPPO : Suleimaniyah' },
{ label: 'ALEPPO : Suweiqah' },
{ label: 'ALEPPO : Tal az-Zarazir' },
{ label: 'ALEPPO : University Square' },
{ label: 'ALEPPO : Zabadiyah' },
{ label: 'ALEPPO : Zahra' },
{ label: 'ALEPPO : Zara\'a roundabout' },
{ label: 'ALEPPO : Abbad' },
{ label: 'ALEPPO : Abbin Samaan' },
{ label: 'ALEPPO : Ablah' },
{ label: 'ALEPPO : Abzemu' },
{ label: 'ALEPPO : Afrin' },
{ label: 'ALEPPO : Akhtarin' },
{ label: 'ALEPPO : Amarnah' },
{ label: 'ALEPPO : Arima' },
{ label: 'ALEPPO : Ayn al-Arab' },
{ label: 'ALEPPO : Ayoun' },
{ label: 'ALEPPO : Azaz' },
{ label: 'ALEPPO : Al Bab' },
{ label: 'ALEPPO : Babakah' },
{ label: 'ALEPPO : Baraj Abdullah' },
{ label: 'ALEPPO : Bashantara' },
{ label: 'ALEPPO : Bashqatin' },
{ label: 'ALEPPO : Bel' },
{ label: 'ALEPPO : Braghidah' },
{ label: 'ALEPPO : Darat Izzah' },
{ label: 'ALEPPO : Deir Hafir' },
{ label: 'ALEPPO : Ghandawi' },
{ label: 'ALEPPO : Ghouz' },
{ label: 'ALEPPO : Hawwar' },
{ label: 'ALEPPO : Ihtimalat' },
{ label: 'ALEPPO : Irshaf' },
{ label: 'ALEPPO : Asunbul' },
{ label: 'ALEPPO : Jab al-Khass' },
{ label: 'ALEPPO : Jindaris' },
{ label: 'ALEPPO : Kafar Aleppo' },
{ label: 'ALEPPO : Kafar Ameh' },
{ label: 'ALEPPO : Kafar Dael' },
{ label: 'ALEPPO : Kafar Ghan' },
{ label: 'ALEPPO : Kafar Karmin' },
{ label: 'ALEPPO : Kafar Naha' },
{ label: 'ALEPPO : Kafar Naseh' },
{ label: 'ALEPPO : Kafar Naya' },
{ label: 'ALEPPO : Khafisah' },
{ label: 'ALEPPO : Khan al-Asl' },
{ label: 'ALEPPO : Kuwayris Airbase' },
{ label: 'ALEPPO : Madiunah' },
{ label: 'ALEPPO : Manbij' },
{ label: 'ALEPPO : Mansoura' },
{ label: 'ALEPPO : Maqri' },
{ label: 'ALEPPO : Ma\'ranaz' },
{ label: 'ALEPPO : Mar\'e' },
{ label: 'ALEPPO : Maret Artiq' },
{ label: 'ALEPPO : Maryamayn' },
{ label: 'ALEPPO : Masalmiyah' },
{ label: 'ALEPPO : Maskanah' },
{ label: 'ALEPPO : Midanki' },
{ label: 'ALEPPO : Miznaz' },
{ label: 'ALEPPO : Niyarah' },
{ label: 'ALEPPO : Nubl' },
{ label: 'ALEPPO : Qastel Jendu' },
{ label: 'ALEPPO : Mregel' },
{ label: 'ALEPPO : Safirah' },
{ label: 'ALEPPO : Sakriyah Kabira' },
{ label: 'ALEPPO : Sandarah' },
{ label: 'ALEPPO : Sarrin' },
{ label: 'ALEPPO : Shaddar' },
{ label: 'ALEPPO : Shayukh Fuqani' },
{ label: 'ALEPPO : Shweiha' },
{ label: 'ALEPPO : Ta\'anah' },
{ label: 'ALEPPO : Tadif' },
{ label: 'ALEPPO : Tafriah' },
{ label: 'ALEPPO : Talafeh' },
{ label: 'ALEPPO : Tal Aran' },
{ label: 'ALEPPO : Tal Hodan' },
{ label: 'ALEPPO : Tal Jabin' },
{ label: 'ALEPPO : Tal Rifaat' },
{ label: 'ALEPPO : Tal Sullur' },
{ label: 'ALEPPO : Tawwamah' },
{ label: 'ALEPPO : Turkmen al-Bareh' },
{ label: 'ALEPPO : Umayjil' },
{ label: 'ALEPPO : Urum al-Kubra' },
{ label: 'ALEPPO : Zammar' },
{ label: 'ALEPPO : Zerbah' },
{ label: 'ALEPPO : Ziadiyah' },
{ label: 'ALEPPO : Al-Fardos' },
{ label: 'ALEPPO : Ashekh Saeed' },
{ label: 'DAMASCUS : DAMASCUS' },
{ label: 'DAMASCUS : Bahsah' },
{ label: 'DAMASCUS : Beit Saham' },
{ label: 'DAMASCUS : Daf al-Shook' },
{ label: 'DAMASCUS : Jamarek Sq' },
{ label: 'DAMASCUS : Jouret Sherabati' },
{ label: 'DAMASCUS : Khairo Yassin mosque' },
{ label: 'DAMASCUS : Khuzimeh mosque' },
{ label: 'DAMASCUS : Sakhanah Square' },
{ label: 'DAMASCUS : Sidi Moqdad' },
{ label: 'DAMASCUS : Tishreen' },
{ label: 'DAMASCUS : Zein al-Abideen Mosque' },
{ label: 'DAMASCUS : Yarmouk Camp' },
{ label: 'DAMASCUS : Al Midan' },
{ label: 'DAMASCUS : Ruken Al-Din' },
{ label: 'DAMASCUS : Qaboun' },
{ label: 'DAMASCUS : Barzeh' },
{ label: 'DAMASCUS : Jobar' },
{ label: 'DAMASCUS : Kafar souseh' },
{ label: 'DAMASCUS : Babila' },
{ label: 'DAMASCUS : Muadamiyat Al-sham' },
{ label: 'DAMASCUS : Yalda' },
{ label: 'DAMASCUS : Irbin nahiyah' },
{ label: 'DAMASCUS : Jaramana' },
{ label: 'DAMASCUS : Kafar Batna' },
{ label: 'DAMASCUS : Kiswah' },
{ label: 'DAMASCUS : Kiswah nahiyah' },
{ label: 'DAMASCUS : Mleiha' },
{ label: 'DAMASCUS : Daraya mantiqah' },
{ label: 'DAMASCUS : al-Hajar al-Aswad nahiyah' },
{ label: 'DAMASCUS : Sahnaya nahiyah' },
{ label: 'DAMASCUS : Duma' },
{ label: 'DAMASCUS : Dumayr nahiyah' },
{ label: 'DAMASCUS : Harasta nahiyah' },
{ label: 'DAMASCUS : Harran al-Awamid nahiyah' },
{ label: 'DAMASCUS : Nashabiyah nahiyah' },
{ label: 'DAMASCUS : Sabaa Biyar nahiyah' },
{ label: 'DAMASCUS : an-Nabek mantiqah' },
{ label: 'DAMASCUS : Deir Atiyah nahiyah' },
{ label: 'DAMASCUS : Qatana mantiqah' },
{ label: 'DAMASCUS : Beit Jen nahiyah' },
{ label: 'DAMASCUS : Sa\'sa\' nahiyah' },
{ label: 'DAMASCUS : Qudsaya mantiqah' },
{ label: 'DAMASCUS : Ayn al-Fijah nahiyah' },
{ label: 'DAMASCUS : al-Demas nahiyah' },
{ label: 'DAMASCUS : Qudsaya nahiyah' },
{ label: 'DAMASCUS : Qutayfah mantiqah' },
{ label: 'DAMASCUS : Jayrud nahiyah' },
{ label: 'DAMASCUS : Ma\'alula nahiyah' },
{ label: 'DAMASCUS : Ruhaybah nahiyah' },
{ label: 'DAMASCUS : at-Tal mantiqah' },
{ label: 'DAMASCUS : Rankous nahiyah' },
{ label: 'DAMASCUS : Seidnaya nahiyah' },
{ label: 'DAMASCUS : Yabrud mantiqah' },
{ label: 'DAMASCUS : Assal al-Ward nahiyah' },
{ label: 'DAMASCUS : Zabadani mantiqah' },
{ label: 'DAMASCUS : Madaya' },
{ label: 'DAMASCUS : Serghaya nahiyah' },
{ label: 'DAMASCUS : Az-Zabadani nahiyah' },
{ label: 'DAMASCUS : Ghazlaniyah nahiyah' },
{ label: 'DAMASCUS : an-Nabek nahiyah' },
{ label: 'DAMASCUS : Qatana nahiyah' },
{ label: 'DAMASCUS : Ashrafiat Wadi Barada' },
{ label: 'DAMASCUS : Wadi Barada Market' },
{ label: 'DAMASCUS : Jdaydet al-Fadel' },
{ label: 'DAMASCUS : Jdaydet Shibani' },
{ label: 'DARAA : DARAA' },
{ label: 'DARAA : Dahiya Gharbiyah' },
{ label: 'DARAA : Kashef' },
{ label: 'DARAA : Matar' },
{ label: 'DARAA : Qusour' },
{ label: 'DARAA : Sahari' },
{ label: 'DARAA : Arab International (European) Uni' },
{ label: 'DARAA : Bosra' },
{ label: 'DARAA : Dael' },
{ label: 'DARAA : Herak' },
{ label: 'DARAA : Inkhil' },
{ label: 'DARAA : Izraa' },
{ label: 'DARAA : jasim' },
{ label: 'DARAA : Nafiah' },
{ label: 'DARAA : Nawa' },
{ label: 'DARAA : Sanamayn' },
{ label: 'DARAA : Sheikh Miskin' },
{ label: 'DARAA : Tafas' },
{ label: 'DARAA : Kafar Shames' },
{ label: 'DEIR EZZOR : DEIR EZZOR' },
{ label: 'DEIR EZZOR : Abu Kamal mantiqah' },
{ label: 'DEIR EZZOR : Abu Kamal nahiyah' },
{ label: 'DEIR EZZOR : Hajez Jamyan' },
{ label: 'DEIR EZZOR : al-Jalaa nahiyah' },
{ label: 'DEIR EZZOR : as-Souseh nahiyah' },
{ label: 'DEIR EZZOR : Deir ez-Zour mantiqah' },
{ label: 'DEIR EZZOR : Busayrah nahiyah' },
{ label: 'DEIR EZZOR : Deir ez-Zour nahiyah' },
{ label: 'DEIR EZZOR : Kasra nahiyah' },
{ label: 'DEIR EZZOR : Khesham nahiyah' },
{ label: 'DEIR EZZOR : Muhasan nahiyah' },
{ label: 'DEIR EZZOR : Sour nahiyah' },
{ label: 'DEIR EZZOR : At-Tibni nahiyah' },
{ label: 'DEIR EZZOR : al-Mayadin mantiqah' },
{ label: 'DEIR EZZOR : Asharh nahiyah' },
{ label: 'DEIR EZZOR : Dhiban nahiyah' },
{ label: 'DEIR EZZOR : Baloum' },
{ label: 'DEIR EZZOR : Buomar' },
{ label: 'DEIR EZZOR : Dahleh' },
{ label: 'DEIR EZZOR : Ghamam' },
{ label: 'DEIR EZZOR : Hatilah' },
{ label: 'DEIR EZZOR : Mahaymidah' },
{ label: 'DEIR EZZOR : Safirat Tahtaniyah' },
{ label: 'DEIR EZZOR : Sawa\'ih' },
{ label: 'DEIR EZZOR : Shaitat' },
{ label: 'DEIR EZZOR : Shnan' },
{ label: 'DEIR EZZOR : Taybah' },
{ label: 'DEIR EZZOR : Zabari' },
{ label: 'DEIR EZZOR : Al-Sinaa' },
{ label: 'DEIR EZZOR : Hajin nahiyah' },
{ label: 'HAMA : HAMA' },
{ label: 'HAMA : 15 March St' },
{ label: 'HAMA : Abi al-Fida' },
{ label: 'HAMA : Amiriyah' },
{ label: 'HAMA : Aylilat' },
{ label: 'HAMA : Bab al-Balad' },
{ label: 'HAMA : Bab Qebli' },
{ label: 'HAMA : Baraziyah' },
{ label: 'HAMA : Basher al-Hafi mosque' },
{ label: 'HAMA : Bayad' },
{ label: 'HAMA : Burhan Souq (Hader)' },
{ label: 'HAMA : Dabagha' },
{ label: 'HAMA : Farrayah' },
{ label: 'HAMA : Haddadin Souq' },
{ label: 'HAMA : Ibn Rashid St' },
{ label: 'HAMA : Jab roundabout' },
{ label: 'HAMA : Janoob al-Thakneh' },
{ label: 'HAMA : Jarajmeh' },
{ label: 'HAMA : Karam Hourani' },
{ label: 'HAMA : Marabet' },
{ label: 'HAMA : Mashaa al-Tayar' },
{ label: 'HAMA : Al-Madena' },
{ label: 'HAMA : Nasr' },
{ label: 'HAMA : Shamaliyeh' },
{ label: 'HAMA : Sharqiyah' },
{ label: 'HAMA : Sheikh Alwan' },
{ label: 'HAMA : Sheikh Anbar' },
{ label: 'HAMA : Sheikh Mohammed al-Hamid St' },
{ label: 'HAMA : Shuhada mosque' },
{ label: 'HAMA : Souq Taweel' },
{ label: 'HAMA : Taawniyah' },
{ label: 'HAMA : Abu Hanaya' },
{ label: 'HAMA : Abu Rimal' },
{ label: 'HAMA : Amiqiyah' },
{ label: 'HAMA : Aqayribat' },
{ label: 'HAMA : Arba\'een' },
{ label: 'HAMA : Arzeh' },
{ label: 'HAMA : Asharenah' },
{ label: 'HAMA : Ashrafiyah' },
{ label: 'HAMA : Aweinah' },
{ label: 'HAMA : Aziziyah' },
{ label: 'HAMA : Bab al-Taqah' },
{ label: 'HAMA : Balahsin' },
{ label: 'HAMA : Berri al-Sharqi' },
{ label: 'HAMA : Deemu' },
{ label: 'HAMA : Fan Shamali' },
{ label: 'HAMA : Fellah' },
{ label: 'HAMA : Halfaya' },
{ label: 'HAMA : Hamidiyah' },
{ label: 'HAMA : Hammadi al-Omar' },
{ label: 'HAMA : Hanjour' },
{ label: 'HAMA : Hawash' },
{ label: 'HAMA : Hawijah' },
{ label: 'HAMA : Hawiz' },
{ label: 'HAMA : Hayalin' },
{ label: 'HAMA : Jabriyah' },
{ label: 'HAMA : Jadideh' },
{ label: 'HAMA : Jalameh' },
{ label: 'HAMA : Jammaseh' },
{ label: 'HAMA : Jarjarah' },
{ label: 'HAMA : Jarjiseh' },
{ label: 'HAMA : Jayed' },
{ label: 'HAMA : Jennan' },
{ label: 'HAMA : Jibeen' },
{ label: 'HAMA : Jreijas' },
{ label: 'HAMA : Kafar Houd' },
{ label: 'HAMA : Kafar al-Toun' },
{ label: 'HAMA : Kafraa' },
{ label: 'HAMA : Karameh' },
{ label: 'HAMA : Karayam' },
{ label: 'HAMA : Khafsin' },
{ label: 'HAMA : Khnayzir' },
{ label: 'HAMA : Krah' },
{ label: 'HAMA : Latammin' },
{ label: 'HAMA : latamneh' },
{ label: 'HAMA : Ma\'arzaf' },
{ label: 'HAMA : Jubb Al-Aswad' },
{ label: 'HAMA : Marrashidah' },
{ label: 'HAMA : Massoud' },
{ label: 'HAMA : Misyaf' },
{ label: 'HAMA : Morek' },
{ label: 'HAMA : Muhradah' },
{ label: 'HAMA : Mustarihah' },
{ label: 'HAMA : Qaber Fidah' },
{ label: 'HAMA : Qabu' },
{ label: 'HAMA : Qanbar' },
{ label: 'HAMA : Qasr Abu Samrah' },
{ label: 'HAMA : Qassabiyah' },
{ label: 'HAMA : Qubeir' },
{ label: 'HAMA : Qubaybat' },
{ label: 'HAMA : Qulaydin' },
{ label: 'HAMA : Rihajan' },
{ label: 'HAMA : Sabburah' },
{ label: 'HAMA : Safsafeh' },
{ label: 'HAMA : Sahariyah' },
{ label: 'HAMA : Salamiyah' },
{ label: 'HAMA : Samalil' },
{ label: 'HAMA : Sa\'an' },
{ label: 'HAMA : Shaharnaz' },
{ label: 'HAMA : Shari\'ah' },
{ label: 'HAMA : Shayr' },
{ label: 'HAMA : Shayzer' },
{ label: 'HAMA : Sheikh Hadid' },
{ label: 'HAMA : Sheyha' },
{ label: 'HAMA : Sihriyah' },
{ label: 'HAMA : Sormaniyah' },
{ label: 'HAMA : Souha' },
{ label: 'IDLIB : Sukayk' },
{ label: 'HAMA : Suqaylabiyah' },
{ label: 'HAMA : Suran' },
{ label: 'HAMA : Tal Khanzir' },
{ label: 'HAMA : Tal Malah' },
{ label: 'HAMA : Tal Sakkin' },
{ label: 'HAMA : Talaf' },
{ label: 'HAMA : Talisiyah' },
{ label: 'HAMA : Tamana\'at al-Ghab' },
{ label: 'HAMA : Tarmala' },
{ label: 'HAMA : Tayyibat al-Imam' },
{ label: 'HAMA : Tayyibat al-Turki' },
{ label: 'HAMA : Toubah' },
{ label: 'HAMA : Traymseh' },
{ label: 'HAMA : Utshan' },
{ label: 'HAMA : Zakah' },
{ label: 'HAMA : Zeizoun' },
{ label: 'HAMA : Zillakiat' },
{ label: 'HAMA : Khatamlu' },
{ label: 'HAMA : KafrZita' },
{ label: 'HAMA : Al-Boida' },
{ label: 'HAMA : Ziyarah' },
{ label: 'HASAKAH : HASAKAH' },
{ label: 'HASAKAH : Tall Bulayj' },
{ label: 'HASAKAH : Salihiyat Harb' },
{ label: 'HASAKAH : Haddadiyah' },
{ label: 'HASAKAH : al-Arisheh nahiyah' },
{ label: 'HASAKAH : Bir al-Helou nahiyah' },
{ label: 'HASAKAH : al-Hasakah nahiyah' },
{ label: 'HASAKAH : al-Houl nahiyah' },
{ label: 'HASAKAH : Markadeh nahiyah' },
{ label: 'HASAKAH : Shaddadeh nahiyah' },
{ label: 'HASAKAH : Tal Tamer nahiyah' },
{ label: 'HASAKAH : al-Malikiyah mantiqah' },
{ label: 'HASAKAH : Jawadiyah nahiyah' },
{ label: 'HASAKAH : al-Malikiyah nahiyah' },
{ label: 'HASAKAH : Yarubiyeh nahiyah' },
{ label: 'HASAKAH : Qamishli mantiqah' },
{ label: 'HASAKAH : Amouda nahiyah' },
{ label: 'HASAKAH : Qamishli nahiyah' },
{ label: 'HASAKAH : Tal Hamis nahiyah' },
{ label: 'HASAKAH : al-Qahtaniyeh nahiyah' },
{ label: 'HASAKAH : Ras al-Ayn mantiqah' },
{ label: 'HASAKAH : Darbasiyah nahiyah' },
{ label: 'HASAKAH : Ras al-Ayn nahiyah' },
{ label: 'HASAKAH : Khirbet Bajar' },
{ label: 'HASAKAH : Saba Arba\'een' },
{ label: 'HASAKAH : Tawarikh' },
{ label: 'HOMS : HOMS' },
{ label: 'HOMS : Old Homs' },
{ label: 'HOMS : Adawiyah' },
{ label: 'HOMS : A\'iddine Camp' },
{ label: 'HOMS : Asheerah' },
{ label: 'HOMS : Bab Turkman' },
{ label: 'HOMS : Bani Sibai' },
{ label: 'HOMS : Dalati mosque' },
{ label: 'HOMS : Fakhoura' },
{ label: 'HOMS : Hama Street' },
{ label: 'HOMS : Jab al-Jandali' },
{ label: 'HOMS : Karam Shamsham' },
{ label: 'HOMS : Marija' },
{ label: 'HOMS : Rabia al-Arabi' },
{ label: 'HOMS : Rifai' },
{ label: 'HOMS : Sharakes' },
{ label: 'HOMS : Sultaniyah' },
{ label: 'HOMS : Wadi Arab' },
{ label: 'HOMS : Abel' },
{ label: 'HOMS : Al-Burayj' },
{ label: 'HOMS : Dhaba\'ah' },
{ label: 'HOMS : Dar-Assalamlam' },
{ label: 'HOMS : Gharnatah' },
{ label: 'HOMS : Ghasaniyah' },
{ label: 'HOMS : Hallat' },
{ label: 'HOMS : Kafar Laha' },
{ label: 'HOMS : Mahin' },
{ label: 'HOMS : Marmarita' },
{ label: 'HOMS : Muharram' },
{ label: 'HOMS : Naoureh' },
{ label: 'HOMS : Naqirah' },
{ label: 'HOMS : Palmyra' },
{ label: 'HOMS : Qalaat al-Hosn' },
{ label: 'HOMS : Qaryatayn' },
{ label: 'HOMS : Qusayr' },
{ label: 'HOMS : Rastan' },
{ label: 'HOMS : Shihshar' },
{ label: 'HOMS : Sukhnah' },
{ label: 'HOMS : Talbisah' },
{ label: 'HOMS : Talkalakh' },
{ label: 'HOMS : Zafaraneh' },
{ label: 'HOMS : Zara' },
{ label: 'HOMS : Dayr Baalbah' },
{ label: 'HOMS : Al-Khaldeeye' },
{ label: 'HOMS : Ash Shawmariyah' },
{ label: 'HOMS : Taldou' },
{ label: 'HOMS : Ter Maela' },
{ label: 'IDLIB : IDLIB' },
{ label: 'IDLIB : Abadeen' },
{ label: 'IDLIB : Ablin' },
{ label: 'IDLIB : Abu Makki' },
{ label: 'IDLIB : Abu al-Zuhour Airbase' },
{ label: 'IDLIB : Adwan' },
{ label: 'IDLIB : Ajaz' },
{ label: 'IDLIB : Akko' },
{ label: 'IDLIB : Allani' },
{ label: 'IDLIB : Aqrabat' },
{ label: 'IDLIB : Ariha' },
{ label: 'IDLIB : Armala' },
{ label: 'IDLIB : Arnaba' },
{ label: 'IDLIB : Ayn Bayda' },
{ label: 'IDLIB : Ayn Hour' },
{ label: 'IDLIB : Ayn Larouz' },
{ label: 'IDLIB : Ayn Sheeb' },
{ label: 'IDLIB : Azmarin' },
{ label: 'IDLIB : Babullah' },
{ label: 'IDLIB : Babuleen' },
{ label: 'IDLIB : Bafatamoun' },
{ label: 'IDLIB : Balioun' },
{ label: 'IDLIB : Basaida' },
{ label: 'IDLIB : Basqanoul' },
{ label: 'IDLIB : Bashiriyah' },
{ label: 'IDLIB : Bassamas' },
{ label: 'IDLIB : Bawaider' },
{ label: 'IDLIB : Bayates' },
{ label: 'IDLIB : Bazabor' },
{ label: 'IDLIB : Bdama' },
{ label: 'IDLIB : Bikafloun' },
{ label: 'IDLIB : Binein' },
{ label: 'IDLIB : Binnish' },
{ label: 'IDLIB : Bishlamoun' },
{ label: 'IDLIB : Burnan' },
{ label: 'IDLIB : Bzaytah' },
{ label: 'IDLIB : Dadikh' },
{ label: 'IDLIB : Dana' },
{ label: 'IDLIB : Dana village' },
{ label: 'IDLIB : Deir Gharbi' },
{ label: 'IDLIB : Deir Sinbal' },
{ label: 'IDLIB : Deir Sharqi' },
{ label: 'IDLIB : Faqi\'a' },
{ label: 'IDLIB : Farkaya' },
{ label: 'IDLIB : Fatirah' },
{ label: 'IDLIB : Ghafar' },
{ label: 'IDLIB : Hafsarjah' },
{ label: 'IDLIB : Halban' },
{ label: 'IDLIB : Hammameh' },
{ label: 'IDLIB : Hantutin' },
{ label: 'IDLIB : Harbanafsah' },
{ label: 'IDLIB : Harbanoush' },
{ label: 'IDLIB : Harem' },
{ label: 'IDLIB : Hartamiyah' },
{ label: 'IDLIB : Hawaij' },
{ label: 'IDLIB : Haysh' },
{ label: 'IDLIB : Hazano' },
{ label: 'IDLIB : Hazarin' },
{ label: 'IDLIB : Heraki' },
{ label: 'IDLIB : Jadraya' },
{ label: 'IDLIB : Jaradeh' },
{ label: 'IDLIB : Jbala' },
{ label: 'IDLIB : Jisr ash-Shughur' },
{ label: 'IDLIB : Joubas' },
{ label: 'IDLIB : Juzef' },
{ label: 'IDLIB : Kafar Amim' },
{ label: 'IDLIB : Kafar Arouq' },
{ label: 'IDLIB : Kafar Ayn' },
{ label: 'IDLIB : Kafar Batikh' },
{ label: 'IDLIB : Kafar Dariyan' },
{ label: 'IDLIB : Kafar Haya' },
{ label: 'IDLIB : Kafar Houm' },
{ label: 'IDLIB : Kafar Jalis' },
{ label: 'IDLIB : Kafar Kila' },
{ label: 'IDLIB : Kafar Latah' },
{ label: 'IDLIB : Kafar Meed' },
{ label: 'IDLIB : Kafar Nabil' },
{ label: 'IDLIB : Kafar Najed' },
{ label: 'IDLIB : Kafar Ruhin' },
{ label: 'IDLIB : Kafar Sejnah' },
{ label: 'IDLIB : Kafar Shalaya' },
{ label: 'IDLIB : Kafar Takharim' },
{ label: 'IDLIB : Kafar Ziba' },
{ label: 'IDLIB : Kafaraya' },
{ label: 'IDLIB : Kaniset Baniez' },
{ label: 'IDLIB : Kaniset Nakhleh' },
{ label: 'IDLIB : Karratin Al-kebire' },
{ label: 'IDLIB : Karratin Al-seghire' },
{ label: 'IDLIB : Kastan' },
{ label: 'IDLIB : Katian' },
{ label: 'IDLIB : Khan Shaykhun' },
{ label: 'IDLIB : Khan Subul' },
{ label: 'IDLIB : Khawari' },
{ label: 'IDLIB : Khirbet al-Jouz' },
{ label: 'IDLIB : Koukabah' },
{ label: 'IDLIB : Kouin' },
{ label: 'IDLIB : Kursaa' },
{ label: 'IDLIB : Laj' },
{ label: 'IDLIB : Ma\'di' },
{ label: 'IDLIB : Ma\'isrounah' },
{ label: 'IDLIB : Maghara' },
{ label: 'IDLIB : Mahalah' },
{ label: 'IDLIB : Mahambel' },
{ label: 'IDLIB : Majadaliya' },
{ label: 'IDLIB : Mantaf' },
{ label: 'IDLIB : Maisarounah' },
{ label: 'IDLIB : Mar Baleet' },
{ label: 'IDLIB : Mar Dibsah' },
{ label: 'IDLIB : Mar Shamarin' },
{ label: 'IDLIB : Mar Zita' },
{ label: 'IDLIB : Marateh' },
{ label: 'IDLIB : Marat Hermeh' },
{ label: 'IDLIB : Marat Hitat' },
{ label: 'IDLIB : Marat Mattar' },
{ label: 'IDLIB : Maret Misrin' },
{ label: 'IDLIB : Maret Al-khaskah' },
{ label: 'IDLIB : Areha' },
{ label: 'IDLIB : Kourin' },
{ label: 'IDLIB : Urum al-Jouz' },
{ label: 'IDLIB : Ehsem nahiyah' },
{ label: 'IDLIB : al-Barrah' },
{ label: 'IDLIB : Ehsem' },
{ label: 'IDLIB : Kansafrah' },
{ label: 'IDLIB : Mhambel nahiyah' },
{ label: 'IDLIB : Armanaz nahiyah' },
{ label: 'IDLIB : Kafr Takharim nahiyah' },
{ label: 'IDLIB : Qorqania nahiyah' },
{ label: 'IDLIB : Salqin nahiyah' },
{ label: 'IDLIB : Saraqib nahiyah' },
{ label: 'IDLIB : Sarmin nahiyah' },
{ label: 'IDLIB : Taftanaz' },
{ label: 'IDLIB : Darkoush nahiyah' },
{ label: 'IDLIB : al-Janudiyah nahiyah' },
{ label: 'IDLIB : Maret Numan' },
{ label: 'IDLIB : Kafranbel nahiyah' },
{ label: 'IDLIB : Sanjar nahiyah' },
{ label: 'IDLIB : Tamana\'ah nahiyah' },
{ label: 'IDLIB : Maret Sin' },
{ label: 'IDLIB : Mariyan' },
{ label: 'IDLIB : Maratin' },
{ label: 'IDLIB : Mashmashan' },
{ label: 'IDLIB : Ma\'tarem' },
{ label: 'IDLIB : Mouqa' },
{ label: 'IDLIB : Muzrah' },
{ label: 'IDLIB : Nabhan' },
{ label: 'IDLIB : Nahal' },
{ label: 'IDLIB : Nahlaya' },
{ label: 'IDLIB : Nahleh' },
{ label: 'IDLIB : Al Naqeer' },
{ label: 'IDLIB : Qarati' },
{ label: 'IDLIB : Qominas' },
{ label: 'IDLIB : Qouqafin' },
{ label: 'IDLIB : Qourqaniya' },
{ label: 'IDLIB : Rakaya' },
{ label: 'IDLIB : Rami' },
{ label: 'IDLIB : Rayan' },
{ label: 'IDLIB : Rusafa' },
{ label: 'IDLIB : San' },
{ label: 'IDLIB : Sararif' },
{ label: 'IDLIB : Sarjah' },
{ label: 'IDLIB : Saqi\'ah' },
{ label: 'IDLIB : Shagurit' },
{ label: 'IDLIB : Sheikh Idris' },
{ label: 'IDLIB : Sheikh Yusef' },
{ label: 'IDLIB : Shillakh' },
{ label: 'IDLIB : Shughour' },
{ label: 'IDLIB : Shuhah' },
{ label: 'IDLIB : Tah' },
{ label: 'IDLIB : Tahtaya' },
{ label: 'IDLIB : Tal Dabs' },
{ label: 'IDLIB : Tal Karameh' },
{ label: 'IDLIB : Mardikh' },
{ label: 'IDLIB : Tal Sandal' },
{ label: 'IDLIB : Tal Sultan' },
{ label: 'IDLIB : Talheya' },
{ label: 'IDLIB : Termala' },
{ label: 'IDLIB : Termanin' },
{ label: 'IDLIB : Tranbeh' },
{ label: 'IDLIB : Tur Laha' },
{ label: 'IDLIB : Zahera' },
{ label: 'IDLIB : Zarzour' },
{ label: 'IDLIB : Zeiyniyah' },
{ label: 'LATTAKIA : LATTAKIA' },
{ label: 'LATTAKIA : Ali Jamal' },
{ label: 'LATTAKIA : Amoud' },
{ label: 'LATTAKIA : Awainah' },
{ label: 'LATTAKIA : Beir Qaddar mosque' },
{ label: 'LATTAKIA : Joud mosque' },
{ label: 'LATTAKIA : Qneinas' },
{ label: 'LATTAKIA : Raml al-Shamali' },
{ label: 'LATTAKIA : Sidawi' },
{ label: 'LATTAKIA : Sleibeh' },
{ label: 'LATTAKIA : Sleibeh Projects' },
{ label: 'LATTAKIA : Tabayat' },
{ label: 'LATTAKIA : Tijar Souj' },
{ label: 'LATTAKIA : Aku' },
{ label: 'LATTAKIA : obin' },
{ label: 'LATTAKIA : Aydu' },
{ label: 'LATTAKIA : Ayn al-Qantarah' },
{ label: 'LATTAKIA : Dorrin' },
{ label: 'LATTAKIA : Duwayrikah' },
{ label: 'LATTAKIA : Ghanaymiyah' },
{ label: 'LATTAKIA : Haffah' },
{ label: 'LATTAKIA : Jabal Akrad' },
{ label: 'LATTAKIA : Jabal Turkman' },
{ label: 'LATTAKIA : Jableh' },
{ label: 'LATTAKIA : Kabanah' },
{ label: 'LATTAKIA : Kafar Ajouz' },
{ label: 'LATTAKIA : Kansiba' },
{ label: 'LATTAKIA : Dorien' },
{ label: 'LATTAKIA : Marand' },
{ label: 'IDLIB : Al-Najeya' },
{ label: 'LATTAKIA : Marj al-Zawiyah' },
{ label: 'LATTAKIA : Maruniyat' },
{ label: 'LATTAKIA : Mazzin' },
{ label: 'LATTAKIA : Mushayrifah' },
{ label: 'LATTAKIA : Nabi Yunes' },
{ label: 'LATTAKIA : Qardahah' },
{ label: 'LATTAKIA : Rabia' },
{ label: 'LATTAKIA : Rihaniyah' },
{ label: 'LATTAKIA : Salma' },
{ label: 'LATTAKIA : Shalaf' },
{ label: 'LATTAKIA : Shalfatiyah' },
{ label: 'LATTAKIA : Sharifah' },
{ label: 'LATTAKIA : Tardin' },
{ label: 'LATTAKIA : Wadi Basour' },
{ label: 'LATTAKIA : Wadi Shaykhan' },
{ label: 'LATTAKIA : Zanqufah' },
{ label: 'QUINETRA : QUINETRA' },
{ label: 'QUINETRA : Jeba' },
{ label: 'QUINETRA : Bariqa' },
{ label: 'QUINETRA : BeerAjam' },
{ label: 'QUINETRA : Masharah' },
{ label: 'QUINETRA : Majduliyah' },
{ label: 'QUINETRA : Ar-RAQQAH' },
{ label: 'QUINETRA : al-Karamah nahiyah' },
{ label: 'QUINETRA : Ma\'adan nahiyah' },
{ label: 'QUINETRA : as-Sabkhah nahiyah' },
{ label: 'QUINETRA : Tal Abyad mantiqah' },
{ label: 'QUINETRA : Ayn Issa nahiyah' },
{ label: 'QUINETRA : Suluk nahiyah' },
{ label: 'QUINETRA : ath-Thawrah mantiqah' },
{ label: 'QUINETRA : al-Jerniyah nahiyah' },
{ label: 'QUINETRA : al-Mansourah nahiyah' },
{ label: 'QUINETRA : Ali Bajliyah' },
{ label: 'QUINETRA : Dabsi Afnan' },
{ label: 'QUINETRA : Hammam al-Turkman' },
{ label: 'QUINETRA : Kantari' },
{ label: 'QUINETRA : Mashrafiyah' },
{ label: 'QUINETRA : Shabedagh' },
{ label: 'SUWAYDA : SUWAYDA' },
{ label: 'SUWAYDA : Ariqah' },
{ label: 'SUWAYDA : Dama' },
{ label: 'SUWAYDA : al-Ghariyah' },
{ label: 'SUWAYDA : al-Hit' },
{ label: 'SUWAYDA : Hout' },
{ label: 'SUWAYDA : Imtan' },
{ label: 'SUWAYDA : Majadel' },
{ label: 'SUWAYDA : Malah' },
{ label: 'SUWAYDA : al-Mazraa' },
{ label: 'SUWAYDA : al-Mushannaf' },
{ label: 'SUWAYDA : Nimreh' },
{ label: 'SUWAYDA : al-Qurayya' },
{ label: 'SUWAYDA : Salkhid' },
{ label: 'SUWAYDA : Shaqqa' },
{ label: 'SUWAYDA : Surah as-Saghirah' },
{ label: 'SUWAYDA : Thaybin' },
{ label: 'TARTOUS : TARTOUS' },
{ label: 'TARTOUS : Baniyas' },
{ label: 'TARTOUS : Bayda' },
{ label: 'TARTOUS : Duraykish' },
{ label: 'TARTOUS : Duweir Raslan' },
{ label: 'TARTOUS : Hmein' },
{ label: 'TARTOUS : Juneinat Raslan' },
{ label: 'TARTOUS : Mashta al-Helou' },
{ label: 'TARTOUS : Safita' },
{ label: 'DAMASCUS : Ayn Tarma' },
{ label: 'DAMASCUS : Hazzah' },
{ label: 'DAMASCUS : Saqba' },
{ label: 'DAMASCUS : zamalka' },
{ label: 'DAMASCUS : Hammuriyah' },
{ label: 'IDLIB : Tall Manissss' },
{ label: 'DAMASCUS : Adra' },
{ label: 'IDLIB : Jarjanaz' },
{ label: 'ALEPPO : Harithan' },
{ label: 'DAMASCUS : Mazzeh military airport' },
{ label: 'ALEPPO : Front Al-Burayj' },
{ label: 'HAMA : Alsayad' },
{ label: 'DARAA : Athman' },
{ label: 'ALEPPO : Sheikh Maqsoud' },
{ label: 'IDLIB : Afes' },
{ label: 'DAMASCUS : Khan al-Shih' },
{ label: 'HOMS : Al-Ghantu' },
{ label: 'DARAA : Eastern Al-Ghariyah' },
{ label: 'DAMASCUS : Eastern Ghouta' },
{ label: 'ALEPPO : Sarmada' },
{ label: 'ALEPPO : Kafr hamrah' },
{ label: 'HAMA : Kafr Nabudah' },
{ label: 'ALEPPO : Anadan' },
{ label: 'ALEPPO : Hayyan' },
{ label: 'HOMS : Houla' },
{ label: 'DAMASCUS : Misraba' },
{ label: 'ALEPPO : Ahras' },
{ label: 'ALEPPO : Al atarib' },
{ label: 'DAMASCUS : Deir al-Asafir' },
{ label: 'IDLIB : Hobait' },
{ label: 'HAMA : Lahaya' },
{ label: 'DARAA : Tal Alhara' },
{ label: 'DAMASCUS : Marj al sultan' },
{ label: 'IDLIB : Masaran' },
{ label: 'DEIR EZZOR : Al Bukamal' },
{ label: 'HAMA : Mar kbeh' },
{ label: 'HOMS : Al Zafaraneh' },
{ label: 'HOMS : Umm Sharshuh' },
{ label: 'DARAA : Western Al-Ghariyah' },
{ label: 'DARAA : Kafr Nasij' },
{ label: 'IDLIB : Killi' },
{ label: 'ALEPPO : Maarstah' },
{ label: 'IDLIB : Maret Al nasan' },
{ label: 'ALEPPO : Al Hader' },
{ label: 'DARAA : Al soura' },
{ label: 'ALEPPO : Aljzmate' },
{ label: 'DARAA : Aqraba' },
{ label: 'ALEPPO : Atshanah' },
{ label: 'HOMS : Burj qai' },
{ label: 'ALEPPO : Dayr Jamal' },
{ label: 'DAMASCUS : Qalamoun' },
{ label: 'ALEPPO : Sakhour' },
{ label: 'HOMS : San Aswad' },
{ label: 'ALEPPO : Zitan' },
{ label: 'ALEPPO : Bab Qinnesrin' },
{ label: 'HOMS : Aldar alkabera' },
{ label: 'ALEPPO : Aljaser' },
{ label: 'ALEPPO : Al eis' },
{ label: 'HOMS : Al farhanyeh' },
{ label: 'IDLIB : Al ghadfah' },
{ label: 'IDLIB : Al hamidia' },
{ label: 'ALEPPO : Al Hmera' },
{ label: 'ALEPPO : Al Jubeilah' },
{ label: 'DARAA : Al naymah' },
{ label: 'HOMS : Al waer' },
{ label: 'ALEPPO : Al zarba' },
{ label: 'DAMASCUS : Al ashari' },
{ label: 'HAMA : Aqrab' },
{ label: 'ALEPPO : Ashrafieh' },
{ label: 'ALEPPO : Asileh' },
{ label: 'ALEPPO : Az Ziyarah' },
{ label: 'ALEPPO : Bab al salamah' },
{ label: 'ALEPPO : Bayanoun' },
{ label: 'DARAA : Busra al-Harir' },
{ label: 'ALEPPO : Bustan al-Qasr' },
{ label: 'DARAA : Elma' },
{ label: 'HOMS : Ghajar' },
{ label: 'ALEPPO : hardetneen' },
{ label: 'DAMASCUS : Hazrama' },
{ label: 'HAMA : Hirbinafsah' },
{ label: 'HOMS : Jawalak' },
{ label: 'DAMASCUS : Jisrayn' },
{ label: 'ALEPPO : Kafar Kalbin' },
{ label: 'ALEPPO : Kafer Khasher' },
{ label: 'IDLIB : Kafr aweed' },
{ label: 'ALEPPO : Al-Nuzaha' },
{ label: 'ALEPPO : Khalsah' },
{ label: 'ALEPPO : Masaken Hanano' },
{ label: 'HOMS : Mashroua' },
{ label: 'IDLIB : Mdaya' },
{ label: 'ALEPPO : Misqan' },
{ label: 'ALEPPO : Qabtan al Jabal' },
{ label: 'IDLIB : Ram hamdan' },
{ label: 'ALEPPO : Rif al Mohandeseen' },
{ label: 'DARAA : Saida' },
{ label: 'ALEPPO : Sheikh Khider' },
{ label: 'HOMS : Sneisel' },
{ label: 'IDLIB : Talmenes' },
{ label: 'IDLIB : Tell Sultan' },
{ label: 'ALEPPO : Termaneen' },
{ label: 'ALEPPO : Bshantara' },
{ label: 'ALEPPO : Tal msebeen' },
{ label: 'IDLIB : Al nerab' },
{ label: 'HAMA : Al hawash' },
{ label: 'DAMASCUS : Al-Qadam' },
{ label: 'DARAA : Muzayrib' },
{ label: 'DAMASCUS : Al-Bahariyah' },
{ label: 'DAMASCUS : Al-Otaybah' },
{ label: 'ALEPPO : Batbo' },
{ label: 'ALEPPO : Al-Jinah' },
{ label: 'HOMS :  Al Mukarramiyah ' },
{ label: 'ALEPPO : Anjara' },
{ label: 'ALEPPO : Castillo' },
{ label: 'ALEPPO : Jib Al-Qubeh' },
{ label: 'ALEPPO : Asia' },
{ label: 'ALEPPO : Babis' },
{ label: 'ALEPPO : Bezzeh' },
{ label: 'ALEPPO : Bab Al-Maqam' },
{ label: 'ALEPPO : Al-Alamji' },
{ label: 'ALEPPO : Qarlak' },
{ label: 'ALEPPO : Dahret Awad' },
{ label: 'ALEPPO : Karam Homad' },
{ label: 'ALEPPO : Qabr Al-Englizi' },
{ label: 'ALEPPO : Karam Al-Tahan' },
{ label: 'ALEPPO : Yaqed Al Adas' },
{ label: 'ALEPPO : Gaziantep road' },
{ label: 'ALEPPO : Kalaseh' },
{ label: 'ALEPPO : Ra\'ai' },
{ label: 'ALEPPO : Teqad' },
{ label: 'ALEPPO : Kafar beseen' },
{ label: 'ALEPPO : Masaken Al Baladyeh' },
{ label: 'ALEPPO : Dahyet Al asad' },
{ label: 'ALEPPO : New Aleppo' },
{ label: 'ALEPPO : Numan' },
{ label: 'ALEPPO : Jazraya' },
{ label: 'ALEPPO : khan Touman' },
{ label: 'ALEPPO : Al Nayrab' },
{ label: 'ALEPPO : 1070 project' },
{ label: 'ALEPPO : 3000 apartments area' },
{ label: 'ALEPPO : Al Qasemyeh' },
{ label: 'ALEPPO : Binan Al hes' },
{ label: 'ALEPPO : Tal Al Daman' },
{ label: 'ALEPPO : Al Haj bridge' },
{ label: 'ALEPPO : Al mentar' },
{ label: 'ALEPPO : Jaloum district' },
{ label: 'ALEPPO : Al qseyleh' },
{ label: 'ALEPPO : Othmanyeh' },
{ label: 'ALEPPO : Kafar Nouran' },
{ label: 'ALEPPO : Karfur Mall' },
{ label: 'ALEPPO : Ramousah' },
{ label: 'ALEPPO : Electricity association' },
{ label: 'ALEPPO : Mouasalat' },
{ label: 'ALEPPO : Aleppo damascus International road' },
{ label: 'ALEPPO : Zahret Al Mada\'en' },
{ label: 'ALEPPO : Al Houtah' },
{ label: 'ALEPPO : Ard Al Hamra' },
{ label: 'ALEPPO : Halak' },
{ label: 'DAMASCUS : Medaany' },
{ label: 'DAMASCUS : Housh Al Dawahrah' },
{ label: 'ALEPPO : Um Al Karameel' },
{ label: 'IDLIB : Keftein' },
{ label: 'IDLIB : karsa\'a' },
{ label: 'IDLIB : Shanan' },
{ label: 'ALEPPO : Electricity association' },
{ label: 'ALEPPO : Mouasalat' },
{ label: 'ALEPPO : Aleppo damascus International road' },
{ label: 'ALEPPO : Zahret Al Mada\'en' },
{ label: 'ALEPPO : Al Houtah' },
{ label: 'ALEPPO : Ard Al Hamra' },
{ label: 'ALEPPO : Halak' },
{ label: 'DAMASCUS : Medaany' },
{ label: 'DAMASCUS : Housh Al Dawahrah' },
{ label: 'ALEPPO : Um Al Karameel' },
{ label: 'IDLIB : Keftein' },
{ label: 'IDLIB : karsa\'a' },
{ label: 'IDLIB : Shanan' }
];
